kind: Deployment
apiVersion: apps/v1
metadata:
  name: online-shop
  namespace: rolling-update-ns
  labels:
    app: online-shop
spec:
  replicas: 4
  selector:
    matchlabels:
      app: online-shop
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 1. # optional - 1 extra pod can be created during update
      maxUnavailable: 0  # optional - 0 unavailable pods ensure 0 downtime
  template:
    metadata: 
      labels: 
        app: online-shop
    spec:
      containers:
        - name: online-shop
          image: amitabhdevops/online_shop
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "200m"
              memory: "512Mi"
          

