kind: Service
apiVersion: v1
metadata:
  name: online-shop-service
  namespace: recreate-ns
spec:
  selector:
    app: online-shop
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP